### ISSUE TITLE
CRL has expired: CN=client

### ISSUE THREAD

**Issue by slrslr** [Nyr/openvpn-install#352] opened 2017-08-28 21:59 UTC
Hello, as a noob, i spent some time figuring out why my VPN stopped working, client connection stuck at status message:

"VERIFY OK: depth=0, CN=server"

the /var/log/messages at server shown this:

Aug 29 00:46:53 h31 openvpn[11357]: myclientip:45962 VERIFY ERROR: depth=0, error=CRL has expired: CN=client
Aug 29 00:46:53 h31 openvpn[11357]: myclientip:45962 OpenSSL: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned
Aug 29 00:46:53 h31 openvpn[11357]: myclientip:45962 TLS_ERROR: BIO read tls_read_plaintext error
Aug 29 00:46:53 h31 openvpn[11357]: myclientip:45962 TLS Error: TLS object -> incoming plaintext read error
Aug 29 00:46:53 h31 openvpn[11357]: myclientip:45962 TLS Error: TLS handshake failed

Someone got similar issue and solved it like this: https://forums.openvpn.net/viewtopic.php?t=23166#p67004

Can you please allow during installation to set longer period before CRL have to be renewed or an installed option to renew this? What is suggested workaround?

**Comment by Nyr** [comment] 2017-08-28 22:21
Thanks for reporting this issue. A fix will be committed tomorrow.

**Closed** 2017-08-29 15:57 UTC

**Comment by Nyr** [comment] 2017-08-29 16:04
For anyone wondering: this issue will affect more users as they upgrade to OpenVPN 2.4. My opinion is that this is a big problem with the easy-rsa default selected for EASYRSA_CRL_DAYS.

Fortunately the issue is server-side and easy to resolve. Thanks again for the report.

**Comment by 7rack** [comment] 2018-02-24 07:49
if you installed version before  this commited.you can 
```bash 
cd /etc/openvpn/easy-rsa
./easyrsa  gen-crl
```
