### ISSUE TITLE
DNS with Windows 10 (15063.674) OpenVPN Client not resolving

### ISSUE THREAD

**Issue by uncnqrd** [Nyr/openvpn-install#376] opened 2017-11-05 23:25 UTC
I installed using the script and selected to use openDNS server for name resolution but there were no dns statements added to my server.conf.  E.g.

push "dhcp-option DNS 208.67.220.220"

This caused DNS to fail from the client machine unless I changed my client config, Windows DNS for the tunnel adapter, or added the DNS entries to my /etc/openvpn/server.conf

**Comment by Nyr** [comment] 2017-11-05 23:45
I see no reason for that line to be omitted during setup, it's a simple `echo` inside a `case` statement.

I don't think that there is anything wrong with the script in this regard and am unable to reproduce the described issue, so closing unless you can provide steps for reproduction.

**Closed by Nyr** 2017-11-05 23:45 UTC

**Comment by DerfOh** [comment] 2017-11-06 01:59
Strange, I'm having issues with my dns resolving for some reason too. I have the lines:
```
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
```
Added to my server.conf though.

**Comment by Nyr** [comment] 2017-11-06 12:32
@DerfOh that would be a different issue then. If your server is behind NAT, check [this](#138 (comment)).

**Comment by Benman2785** [comment] 2017-12-30 22:11
still not working - also changed DNS servers to others

**Comment by Nyr** [comment] 2017-12-30 22:19
@Benman2785 use your own issue, not this unrelated one.
