### ISSUE TITLE
Script can't detect TUN device

### ISSUE THREAD

**Issue by dargow** [Nyr/openvpn-install#459] opened 2018-05-02 20:05 UTC
When I try run script, I get:
```
The TUN device is not available
You need to enable TUN before running this script
````
since I was fully confident in the included TUN on my VPS, I checked openvp-install.sh.
I found here string:
```
if [[ ! -e /dev/net/tun ]]; then
```
then I changed it to:
```
if [[ ! -e /dev/tun ]]; then
```
and it all worked without problems
It seems that the tun device can not always be in the /dev/net/tun.

Distro: Debian Stretch

**Comment by Nyr** [comment] 2018-05-02 21:45
That's interesting because even the driver documentation names `/dev/net/tun` as the right path for the device. A "real" machine (not a container) with Debian Stretch will certainly use that.

I'd bet that you are running some kind of container or virtual environment which could be using that unusual path. Please let me know what kind of environment is this VPS running on, so I can reproduce the issue. If you are not running the host and you are renting this server from some provider, I'd appreciate if you can reveal the name of the provider or virtualisation technology which they are using, because I've never seen this in Linux.

If by any chance this is some kind of special setup which you don't want to discuss in public, feel free to email me instead.

**Comment by dargow** [comment] 2018-05-03 05:40
Indeed, the technology of virtualization OpenVZ.
I also checked the tun devices on other providers with the same technology openvz - in all cases there was no device /dev/net/tun, but exist /dev/tun.
Perhaps this is due to the features of cheap vps project lowendspirit.

**Comment by Nyr** [comment] 2018-05-03 12:09
Something must be wrong...

Before you edited your message, I did see that you are running this in LowEndSpirit. This script is very popular among LES users, so I don't understand how only you are having this issue.

> I also checked the tun devices on other providers with the same technology openvz - in all cases there was no device /dev/net/tun, but exist /dev/tun.

This simply can't be like that, OpenVZ is a very popular virtualization technology and thousands of users are running this script there. I myself have a OpenVZ container which indeed has the TUN device at `/dev/net/tun`.

Can you please run the following commands in your affected container and paste the output here?
`cat /dev/net/tun`
`cat /dev/tun`

Additionally, could you please let me know which specific LES location are you using?

**Comment by dargow** [comment] 2018-05-03 19:33
It took some time to test.
1. DeepNetSolutions
1.1 
Location - DE
TUN - Enabled
```
dargod@de:~$ cat /dev/net/tun
cat: /dev/net/tun: File descriptor in bad state
dargod@de:~$ cat /dev/tun
cat: /dev/tun: File descriptor in bad state
```
1.2
Location - ZA
TUN - Enabled
```
dargod@esphost:~$ cat /dev/net/tun
cat: /dev/net/tun: No such file or directory
dargod@esphost:~$ cat /dev/tun 
cat: /dev/tun: File descriptor in bad state
```
2. Gullos Hosting
2.1
Location - BG
TUN - Enabled
```
root@bg:~# cat /dev/net/tun
cat: /dev/net/tun: File descriptor in bad state
root@bg:~# cat /dev/tun
cat: /dev/tun: File descriptor in bad state
```
2.2
Location - FIN
TUN - Disabled
```
root@fi:~# cat /dev/net/tun
cat: /dev/net/tun: No such file or directory
root@fi:~# cat /dev/tun
cat: /dev/tun: No such file or directory
```
3. RansomIT
3.1
Location - AU
TUN - Enabled
```
dargod@auhost:~$ cat /dev/net/tun
cat: /dev/net/tun: No such file or directory
dargod@auhost:~$ cat /dev/tun
cat: /dev/tun: File descriptor in bad state
```
I could not find the patterns in the presence or absence of the device /dev/net/tun, but seems like /dev/tun exists in any case.
Perhaps I need more tests?

**Comment by Nyr** [comment] 2018-05-04 20:09
Just to update you in the current situation:

- Yesterday I tried purchasing from DeepNet, but unfortunately my order was flagged as fraud.
- I sent a ticket trying to get my order verified, but it has been ignored. I was well aware that they provide no support via tickets, but I was not going to send them personal information in the public support forum.

Anyway, my plan was to verify that everything was to further troubleshoot the situation in one of the affected containers and check that everything else was fine before committing an update to the script. I will consider an alternative path if I am unable to get my service with DeepNet activated, but it will probably take some more days since the weekend is already here.

**Comment by Nyr** [comment] 2018-05-05 01:33
Sorry to bother you again: could you please do me one last favor?

- In your **South African** or **Australian** VPS.
- With **TUN enabled** and **OpenVPN installed** and working.

Run the following command:
`ovpnpid=$(pgrep openvpn); ls -l /proc/$ovpnpid/fd/`

And let me know the output. That would be really useful.

**Comment by Nyr** [comment] 2018-05-07 10:28
I bought a DeepNet Solutions VPS in South Africa and are unable to reproduce.

```
root@jnb1:~# cat /dev/net/tun
cat: /dev/net/tun: File descriptor in bad state
root@jnb1:~# cat /dev/tun
cat: /dev/tun: No such file or directory
```

So I am closing this issue unless you are able to help me reproducing the issue, or someone else can help. At this point, the best way would be to email me login details for one of the affected machines.

**Closed by Nyr** 2018-05-07 10:28 UTC

**Comment by its0x08** [comment] 2018-09-25 07:17
I get the same error but the difference is that when i do `cat /dev/tun` or `cat /dev/net/tun` says that it doesnt exist..
any suggestion 
uname: `Linux vps43212.inmotionhosting.com 3.16.0-042stab130.1 #1 SMP Tue May 22 09:19:34 MSK 2018 x86_64 GNU/Linux`

**Comment by Nyr** [comment] 2018-09-25 13:36
@its0x08 probably not the same issue. You likely need to enable TUN in your VPS provider's control panel. If you don't know how to do that, contact them.

**Comment by aria-sayyaf** [comment] 2021-06-28 14:59
and also > distro : centos

**Comment by denisemenov** [comment] 2023-02-05 14:41
> I get the same error but the difference is that when i do `cat /dev/tun` or `cat /dev/net/tun` says that it doesnt exist.. any suggestion uname: `Linux vps43212.inmotionhosting.com 3.16.0-042stab130.1 #1 SMP Tue May 22 09:19:34 MSK 2018 x86_64 GNU/Linux`

I'm a bit late, but for users like me, I'll leave it here. 😁
`mkdir -p /dev/net
mknod /dev/net/tun c 10 200
chmod 600 /dev/net/tun
`
