### ISSUE TITLE
Problem with internet on port : 443 proto : TCP

### ISSUE THREAD

**Issue by kevincaradant** [Nyr/openvpn-install#73] opened 2015-09-30 19:12 UTC
Hi,

Sorry to ask that but after two days and one hundred iptable , i m so lost.

I can connect me to my vpn with a "Initialization Sequence Completed" but i can't go on internet and no ping in external but i can join my vpn ( the server ).

Do you have a idea which is the problem ? 

Thank you a lot :) 

Edit : Same problem with that : https://github.com/tinfoil/openvpn_autoconfig

Server.conf
mode server
proto 
port  
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh1024.pem
tls-auth ta.key 0
cipher AES-256-CBC
server 10.8.0.0 255.255.255.0
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
user nobody
group nogroup
chroot /etc/openvpn/chroot
persist-key
persist-tun
comp-lzo
verb 3
mute 20
status openvpn-status.log
log-append .log

client.conf
client
nobind
dev tun
redirect-gateway def1 bypass-dhcp
remote 212.47.XXX.X443 tcp
comp-lzo yes

<key>
-----BEGIN RSA PRIVATE KEY-----
key here
-----END RSA PRIVATE KEY-----
</key>
<cert>
-----BEGIN CERTIFICATE-----
key here-----END CERTIFICATE-----
</cert>
<ca>
-----BEGIN CERTIFICATE-----
key here
-----END CERTIFICATE-----
</ca>
''
And that maybe will help you  but i don't understand it really :/
![image](https://cloud.githubusercontent.com/assets/6093175/10203952/5291dec6-67b9-11e5-83e9-dcfeff69b81d.png)

**Comment by soko1** [comment] 2015-10-01 07:22
Hi!
On the client computer:

iptables_rules_file:
```
*filter
:INPUT DROP [145:11482]
:FORWARD DROP [0:0]
:OUTPUT DROP [18518:3426455]
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -d XXX.XXX.XXX.XXX/32 -p tcp -j ACCEPT
-A OUTPUT -d XXX.XXX.XXX.XXX/32 -p udp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o tun0 -j ACCEPT
-A OUTPUT -o tun1 -j ACCEPT
COMMIT
```
iptables-restore<iptables_rules_file

XXX.XXX.XXX.XXX - external address vpn-server

**Comment by kevincaradant** [comment] 2015-10-01 10:10
Sorry but i tried with successfull :/  . I tried that on my client machine : 
*filter
:INPUT DROP [145:11482]
:FORWARD DROP [0:0]
:OUTPUT DROP [18518:3426455]
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -d XXX.XXX.XXX.XXX/32 -p tcp -j ACCEPT
-A OUTPUT -d XXX.XXX.XXX.XXX/32 -p udp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o tun0 -j ACCEPT
-A OUTPUT -o tun1 -j ACCEPT
COMMIT

i'm not sure to replace XXX.XXX.XXX.XXX , IP Public of server or something with the route like 192.168.255.0 or the line on server.conf "server 10.8.0.0 255.255.255.0" ? 

this iptables , i have to write on server or client machine ? i thought the problem was on the server not the client machine ? Sorry i'm confused with that :/

**Comment by Nyr** [comment] 2015-10-01 10:17
Not sure why @soko1 published those random rules but you don't need them.

@kevincaradant you shouldn't need to set any additional iptables configuration, my script already does this for you. Anyway, try with a clean Debian/Ubuntu/CentOS install.

This issue doesn't seem to be caused by the script, so closing.

**Closed by Nyr** 2015-10-01 10:17 UTC

**Comment by kevincaradant** [comment] 2015-10-01 10:20
It's already on a clean install @Nyr :).
I will try this afternoon again but i used A VPS with a new install of Ubuntu 15.04. So it's for that i don't understand the problem :/

**Comment by Nyr** [comment] 2015-10-01 10:22
On a clean install, you should need zero additional firewall rules.

If the problem persists, is most likely client-side.

**Comment by kevincaradant** [comment] 2015-10-01 15:58
OKi thank you Nyr and soko1 , i will check that ;)
