### ISSUE TITLE
Issues under Ubuntu 18.04

### ISSUE THREAD

**Issue by IceReaper** [Nyr/openvpn-install#602] opened 2019-04-19 19:44 UTC
Running the script failed under Ubuntu 18.04.
After some digging, the following two copy lines have to be added to make the script work:
```
        ./easyrsa init-pki
        cp openssl-easyrsa.cnf pki/
        cp -r x509-types pki/
        ./easyrsa --batch build-ca nopass
```

**Comment by Nyr** [comment] 2019-04-24 11:53
This is not needed, whatever your issue was.

**Comment by TinCanTech** [comment] 2019-04-24 12:36
Since releasing EasyRSA-306 we have had a small number of similar reports as this but have not managed to establish a precise cause.

**Comment by Nyr** [comment] 2019-04-24 13:05
Thanks @TinCanTech and sorry for discarding your report so fast, @IceReaper.

@IceReaper are you able to provide some details of your setup, so the issue can maybe be reproduced?

It's nearly 3 months since the script upgraded to the conflicting EasyRSA version and this is the first report here, so the issue must indeed be very rare, but it deserves attention nonetheless. I will take a look at this ASAP.

**Comment by TinCanTech** [comment] 2019-04-24 13:42
@Nyr  There are two considerations while upgrading to 3.0.6:

- The first, which is probably related to this issue, is where `./openssl-easyrsa.cnf` is expected to be found.  The behaviour was changed slightly to _prefer_ `./pki/openssl-easyrsa.cnf` .. however `./openssl-easyrsa.cnf` should still work but on rare occasions this issue has arisen. see: https://github.com/OpenVPN/easy-rsa/issues/259

- There are now extra directories for revoked certificates, which has also had at least one issue. see: https://github.com/OpenVPN/easy-rsa/issues/302

The changes are not difficult to understand but they have proven to be a little more trouble than expected.  It may make sense to roll your script back to 3.0.5 but that is completely at your discretion.

@IceReaper **error** messages would be of some use.

**Comment by Nyr** [comment] 2019-04-24 14:57
Thanks, I was aware of the second part but not the first.

I have now [reverted](https://github.com/Nyr/openvpn-install/commit/d4efae3b1081867ffce420267f8c20a7c7336047) to easy-rsa v3.0.5 for the time being and will upgrade to the version which fixes this issue.

Since the script will now be fine for users suffering from this, I'm closing the issue. But @IceReaper, feel free to provide the requested logs if you are able to.

**Closed by Nyr** 2019-04-24 14:57 UTC
