### ISSUE TITLE
Connecting on my machine but not on others. 

### ISSUE THREAD

**Issue by Stsosz** [Nyr/openvpn-install#196] opened 2016-09-13 12:47 UTC
I have been running OpenVPN with your script and it has been running perfectly for me, but nobody apart from me can connect to the server. I make a new <theirname>.ovpn with the script, move it to another computer via USB drive, and install it with Tunnelblick as the client. It gets stuck on "Waiting for server response." If i use the .ovpn on my computer, it works perfectly. Both clients are on the same network. 

Other info:
I am using Ubuntu 14.04 on Digitalocean. 
I am using SSH keys to authenticate myself to the server. 
No changes are made to the server. I create it, SSH in to root, and install your script while in root user. 

Are there any logs I can provide to help diagnose the issue?

**Comment by Nyr** [comment] 2016-09-13 14:16
Are you 100 % sure that you generated new certificates for each client?

If so, and considering that clients are sharing the same network, it is pretty obvious where the problem is ;)

Please, provide the client connection log (Tunnelblick) and let's see if there is anything helpful there.

Closing since the issue doesn't seem to be a problem with the script itself.

**Closed by Nyr** 2016-09-13 14:16 UTC
