### ISSUE TITLE
do not ask for support here...

### ISSUE THREAD

**Issue by dougalx** [Nyr/openvpn-install#491] opened 2018-07-12 19:21 UTC
...then, where?

**Comment by TinCanTech** [comment] 2018-08-07 12:09
@Nyr .. openvpn.net does **not** support your script .. You do.

**Comment by Nyr** [comment] 2018-08-07 12:33
This was obvious for me, but maybe it isn't for everyone, so let me clarify:

- You are not entitled for any kind of support. Is not a matter of where to get it. My work is provided as is with no further guarantees of any kind. Specially no guarantees of free, individualised support.
- I sometimes try to help users which post in this issue tracker, even when their issue has nothing to do with my work. This is done in a best effort basis and I am unable to provide individualised attention to everyone.
- I do support the script. This means that the script is always updated and maintained to work with the supported distros. This doesn't mean that I will provide technical assistance to any user with any issue which they will experience.
- I usually refer people to the OpenVPN forums as one of the best channels to get help troubleshooting issues, with OpenVPN, yeah. If I suspect that the issue has anything to do with my script, which is very rarely the case, I always try troubleshoot the issue with the user myself.

@TinCanTech if you have really found a bug with the script, open a new issue documenting it in this tracker and it will be fixed ASAP.

To everyone else wondering about the unusual backlog of open issues: there is some real life stuff which is keeping my mind busy. Additionally, it is summer and I prefer to enjoy friends than to sit in front of my computer. Rest assured that this project is not abandoned and any urgent issue would still be dealt with promptly.

**Closed by Nyr** 2018-08-07 12:33 UTC

**Comment by TinCanTech** [comment] 2018-08-07 12:46
I agree with your intention to offer the script _as is_ but not your decision to refer people to openvpn for support.  The problem is that people use your script blindly expecting it to work and when it does not they think we can help.  I recommend that instead of referring people to the Forum per se that you ask them to read this:
https://forums.openvpn.net/viewtopic.php?f=30&t=22603


As for the bug .. I shall report it as an issue.  Needless to say, if you did provide support you would know of it and have it fixed by now ..

**Comment by Nyr** [comment] 2018-08-07 13:04
@TinCanTech the users I refer always have connectivity issues, configuration problems or similar "general" issues with OpenVPN. Still, I understand your point and see that it can be a frustrating situation. I will have that in mind for the future.

Believe it or not, I provide lots of support for my users. Still, I am not aware of any known bug at this time and would be very grateful if you can briefly report it so it can be fixed.
