### ISSUE TITLE
server behind NAT. connected but no traffic routed

### ISSUE THREAD

**Issue by coolcow** [Nyr/openvpn-install#377] opened 2017-11-07 19:22 UTC
First: Very awesome script, and works perfectly on my root server! Thank you very much for your work and for sharing it with the world !

Second: yes i HAVE read the issues and searched for a solution there (yes, also: https://github.com/Nyr/openvpn-install/issues/138#issuecomment-196055353) ;)

My RaspberryPi have OpenmediaVault installed (v3.0.91 and up to date). I didn't made any changes to the iptables or anything. I just downloaded and executed the script following the instructions (leaving everything at defaults except for the public ip address).

```
Welcome to this quick OpenVPN "road warrior" installer

I need to ask you a few questions before starting the setup
You can leave the default options and just press enter if you are ok with them

First I need to know the IPv4 address of the network interface you want OpenVPN
listening to.
IP address: 192.168.178.27

Which protocol do you want for OpenVPN connections?
   1) UDP (recommended)
   2) TCP
Protocol [1-2]: 1

What port do you want OpenVPN listening to?
Port: 1194

Which DNS do you want to use with the VPN?
   1) Current system resolvers
   2) Google
   3) OpenDNS
   4) NTT
   5) Hurricane Electric
   6) Verisign
DNS [1-6]: 1

Finally, tell me your name for the client certificate
Please, use one word only, no special characters
Client name: FARM

Okay, that was all I needed. We are ready to setup your OpenVPN server now
Press any key to continue...
Ign file:  InRelease
Ign file:  Release.gpg                                                                                            
Ign file:  Release                                                                                                 
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]                     
```
...
```Looks like your server is behind a NAT!

If your server is NATed (e.g. LowEndSpirit), I need to know the external IP
If that's not the case, just ignore this and leave the next field blank
External IP: *PUBLIC_SERVERIP_HERE*

Finished!

Your client configuration is available at /root/FARM.ovpn
If you want to add more clients, you simply need to run this script again!
```
I masked my real public ip address here for obvious reasons, but i did put the right one there...

The router redirects port 1194 (UDP) to the internal ip `192.168.178.27`.

I can now establish a VPN connection and ping and even ssh into `10.8.0.1`.

```
Tue Nov  7 19:51:54 2017 Unrecognized option or missing parameter(s) in SMS2.ovpn:15: block-outside-dns (2.3.10)
Tue Nov  7 19:51:54 2017 OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
Tue Nov  7 19:51:54 2017 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Tue Nov  7 19:51:54 2017 Control Channel Authentication: tls-auth using INLINE static key file
Tue Nov  7 19:51:54 2017 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Nov  7 19:51:54 2017 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Nov  7 19:51:54 2017 Socket Buffers: R=[212992->212992] S=[212992->212992]
Tue Nov  7 19:51:54 2017 UDPv4 link local: [undef]
Tue Nov  7 19:51:54 2017 UDPv4 link remote: [AF_INET]*PUBLIC_SERVERIP_HERE*:1194
Tue Nov  7 19:51:54 2017 TLS: Initial packet from [AF_INET]*PUBLIC_SERVERIP_HERE*:1194, sid=b384f8c1 ae169ee8
Tue Nov  7 19:51:54 2017 VERIFY OK: depth=1, CN=ChangeMe
Tue Nov  7 19:51:54 2017 Validating certificate key usage
Tue Nov  7 19:51:54 2017 ++ Certificate has key usage  00a0, expects 00a0
Tue Nov  7 19:51:54 2017 VERIFY KU OK
Tue Nov  7 19:51:54 2017 Validating certificate extended key usage
Tue Nov  7 19:51:54 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue Nov  7 19:51:54 2017 VERIFY EKU OK
Tue Nov  7 19:51:54 2017 VERIFY OK: depth=0, CN=server
Tue Nov  7 19:51:54 2017 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Tue Nov  7 19:51:54 2017 Data Channel Encrypt: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Nov  7 19:51:54 2017 Data Channel Decrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Tue Nov  7 19:51:54 2017 Data Channel Decrypt: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Nov  7 19:51:54 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA
Tue Nov  7 19:51:54 2017 [server] Peer Connection Initiated with [AF_INET]*PUBLIC_SERVERIP_HERE*:1194
Tue Nov  7 19:51:57 2017 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Tue Nov  7 19:51:57 2017 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 192.168.178.1,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0'
Tue Nov  7 19:51:57 2017 OPTIONS IMPORT: timers and/or timeouts modified
Tue Nov  7 19:51:57 2017 OPTIONS IMPORT: --ifconfig/up options modified
Tue Nov  7 19:51:57 2017 OPTIONS IMPORT: route options modified
Tue Nov  7 19:51:57 2017 OPTIONS IMPORT: route-related options modified
Tue Nov  7 19:51:57 2017 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Tue Nov  7 19:51:57 2017 ROUTE_GATEWAY 192.168.17.1/255.255.255.0 IFACE=enp4s0 HWADDR=1c:6f:65:c7:e5:fe
Tue Nov  7 19:51:57 2017 TUN/TAP device tun1 opened
Tue Nov  7 19:51:57 2017 TUN/TAP TX queue length set to 100
Tue Nov  7 19:51:57 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Tue Nov  7 19:51:57 2017 /sbin/ip link set dev tun1 up mtu 1500
Tue Nov  7 19:51:57 2017 /sbin/ip addr add dev tun1 10.8.0.2/24 broadcast 10.8.0.255
Tue Nov  7 19:51:57 2017 /sbin/ip route add *PUBLIC_SERVERIP_HERE*/32 via 192.168.17.1
Tue Nov  7 19:51:57 2017 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1
Tue Nov  7 19:51:57 2017 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1
Tue Nov  7 19:51:57 2017 Initialization Sequence Completed
```

But other then that, nothing works. I can't ping any internet ips (`8.8.8.8`, ...) and no ips on the server side (`192.168.178.27`, `192.168.178.1`, ...). The ips on my local network (`192.168.17.1`, ...) are working fine.

I think there have to be something wrong with the routing or iptables, but i don't know what.

Client:
```
vpnclient:~# ip route
0.0.0.0/1 via 10.8.0.1 dev tun0 
default via 192.168.17.1 dev enp4s0  proto static  metric 100 
10.8.0.0/24 dev tun0  proto kernel  scope link  src 10.8.0.2 
*PUBLIC_SERVERIP_HERE* via 192.168.17.1 dev enp4s0 
128.0.0.0/1 via 10.8.0.1 dev tun0 
169.254.0.0/16 dev enp4s0  scope link  metric 1000 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.17.0/24 dev enp4s0  proto kernel  scope link  src 192.168.17.17  metric 100 
```
Server:
```
vpnserver:~# ip route
default via 192.168.178.1 dev eth0 
10.8.0.0/24 dev tun0  proto kernel  scope link  src 10.8.0.1 
169.254.0.0/16 dev eth0  scope link  metric 1000 
192.168.178.0/24 dev eth0  proto kernel  scope link  src 192.168.178.27 
```

I would be more then happy to provide more informations if asked to.

Greets from France !

**Comment by Nyr** [comment] 2017-11-07 19:31
Thanks a lot for the very complete report.

I am not familiar with OpenMediaVault and it is unsupported, but I heard that it works. There could be an issue with your firewall or with your network, looks like the script did its work fine.

Just to double check, please paste the output of this:

`iptables -L`
`iptables -L -t nat`

I am closing because the issue is not with the script, but we can continue troubleshooting, just let me know the output of that.

**Closed by Nyr** 2017-11-07 19:31 UTC

**Comment by coolcow** [comment] 2017-11-07 19:42
Freaking fast reaction ! 

```
root@vpnserver:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
```

```
root@vpnserver:~# iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
SNAT       all  --  10.8.0.0/24         !10.8.0.0/24          to:0.0.0.0
SNAT       all  --  10.8.0.0/24         !10.8.0.0/24          to:192.168.178.27
```

**Comment by nenominal** [comment] 2017-11-07 19:45
Why do you have a SNAT rule for 0.0.0.0?

**Comment by coolcow** [comment] 2017-11-07 19:48
I don't know where this comes from. :/

I remove it and try again later (my wife wants me to eat something first ^^)...

**Comment by Nyr** [comment] 2017-11-07 19:50
That's indeed the issue. That was not added by the script.

Rules are processed in order so that's why the second rule, added by the script, isn't working.

**Comment by coolcow** [comment] 2017-11-07 19:54
I couldn't not resist and tried it before eating.

It works now !!!

The traffic is now routed through the VPN. Thank you so much !!!

Do you have any donation address (Patreon or something else)?

**Comment by Nyr** [comment] 2017-11-07 20:03
Good to know that it's working.

Donations are accepted via [PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=VBAYDL34Z7J6L) or [Bitcoin](https://pastebin.com/raw/M2JJpQpC).

Please note that donations are voluntary, they will never be a form of payment in exchange for better help/support or anything like that.
