### ISSUE TITLE
Permission issue trouble on centos 7

### ISSUE THREAD

**Issue by shakisha** [Nyr/openvpn-install#121] opened 2016-02-11 18:13 UTC
Freshly executed the script and at the end of the script it tells:

    456
    Job for openvpn@server.service failed because the control process exited with error code. See "systemctl status openvpn@server.service" and "journalctl -xe" for details.

>journalctl -xe 
Feb 11 19:12:29 localhost.localdomain openvpn[12736]: Options error: --crl-verify fails with '/etc/openvpn/easy-rsa/pki/crl.pem': Permission denied
Feb 11 19:12:29 localhost.localdomain openvpn[12736]: Options error: Please correct these errors.

**Comment by shakisha** [comment] 2016-02-11 18:39
Same trouble on centos 6.7 

(Feb 11 19:36:40 localhost openvpn[2482]: Options error: --crl-verify fails with '/etc/openvpn/easy-rsa/pki/crl.pem': Permission denied)

**Comment by lukebarone** [comment] 2016-02-11 20:02
You're running as `root`, correct? Or, at least, running the script with `sudo`?

**Comment by shakisha** [comment] 2016-02-11 21:08
yes, running with root user, without any sudo command (on cent fresh minimal installation)

**Comment by Nyr** [comment] 2016-02-11 21:29
Are you using SELinux?

Let me know the output of `sestatus`.

**Comment by shakisha** [comment] 2016-02-11 23:31
disabled

**Comment by Nyr** [comment] 2016-02-11 23:43
Then I don't understand what's going on.

Can you show us the output of `ls -l /etc/openvpn/easy-rsa/pki/crl.pem`?

What's the source of your CentOS installation? A template? Who created it? Looks like there is something non-standard with your setup.

**Comment by shakisha** [comment] 2016-02-12 01:12
I’m really sorry, was the selinux enforcing rule (default on centos).

Is a normal handling from the script? Can the script have a way to understand if selinux it’s enabled and alert the user? 


Roberto Innaimi
roberto.innaimi@gmail.com

**Comment by Nyr** [comment] 2016-02-12 01:16
SELinux is not enabled by default in CentOS AFAIK. That's why the script doesn't deal with it.

Did you install from the ISO or were using a premade template? Asking because my experience with CentOS is very limited.

**Comment by shakisha** [comment] 2016-02-12 01:24
Yes, installed from centos 6.6 minimal and updated with "yum update -y", really strange

**Comment by Nyr** [comment] 2016-02-12 01:28
It's possible that I made a mistake during testing and SELinux needs to be supported indeed.

I will double check this, look at what the defaults are and what's the best approach to improve the situation.

**Comment by Nyr** [comment] 2016-02-12 01:53
Issue confirmed. I'm very sleepy now but will submit a fix tomorrow.

Thanks a lot for reporting it.

**Comment by shakisha** [comment] 2016-02-12 02:01
you are really great :+1:   have a nice night

**Comment by Nyr** [comment] 2016-02-12 22:48
This has been addressed in https://github.com/Nyr/openvpn-install/commit/f9dafd6ec6911475a290b4b565ca0e43319b1b6a.

Thanks again for the report.

**Closed by Nyr** 2016-02-12 22:48 UTC

**Comment by saydulk** [comment] 2017-08-04 20:13
I am using Centos 7 and getting same error: 

[root@server ~]# systemctl start openvpn@server.service
Job for openvpn@server.service failed because the control process exited with error code. See "systemctl status openvpn@server.service" and "journalctl -xe" for details.

**Comment by Nyr** [comment] 2017-08-04 21:36
@saydulk not the same issue, but no one can tell you what's wrong without the logs.
