### ISSUE TITLE
Install fails on Debian Stretch

### ISSUE THREAD

**Issue by fbearoff** [Nyr/openvpn-install#322] opened 2017-06-17 15:40 UTC
Here is the install log:

Saving to: ‘/root/EasyRSA-3.0.1.tgz’

/root/EasyRSA-3.0.1.tgz                                     100%[========================================================================================================================================>]  40.00K   253KB/s    in 0.2s

2017-06-17 17:19:44 (253 KB/s) - ‘/root/EasyRSA-3.0.1.tgz’ saved [40960/40960]

mv: cannot stat '/etc/openvpn/EasyRSA-3.0.1/': No such file or directory
chown: cannot access '/etc/openvpn/easy-rsa/': No such file or directory
openvpn-install.sh: line 243: cd: /etc/openvpn/easy-rsa/: No such file or directory
openvpn-install.sh: line 245: ./easyrsa: No such file or directory
openvpn-install.sh: line 246: ./easyrsa: No such file or directory
openvpn-install.sh: line 247: ./easyrsa: No such file or directory
openvpn-install.sh: line 248: ./easyrsa: No such file or directory
openvpn-install.sh: line 249: ./easyrsa: No such file or directory
openvpn-install.sh: line 250: ./easyrsa: No such file or directory
cp: cannot stat 'pki/ca.crt': No such file or directory
cp: cannot stat 'pki/private/ca.key': No such file or directory
cp: cannot stat 'pki/dh.pem': No such file or directory
cp: cannot stat 'pki/issued/server.crt': No such file or directory
cp: cannot stat 'pki/private/server.key': No such file or directory
cp: cannot stat '/etc/openvpn/easy-rsa/pki/crl.pem': No such file or directory
chown: cannot access '/etc/openvpn/crl.pem': No such file or directory
234
Job for openvpn@server.service failed because the control process exited with error code.
See "systemctl status openvpn@server.service" and "journalctl -xe" for details.
cat: /etc/openvpn/easy-rsa/pki/ca.crt: No such file or directory
cat: /etc/openvpn/easy-rsa/pki/issued/home.crt: No such file or directory
cat: /etc/openvpn/easy-rsa/pki/private/home.key: No such file or directory

Finished!

**Comment by Nyr** [comment] 2017-06-17 16:03
Goddamnit, releasing a mayor upgrade on a saturday afternoon... 

The final Debian Stretch ISOs are still not available, did you upgrade from the repos?

Either way, you omitted the most important part of the log: did the openvpn package install successfully? Because it looks like it didn't, maybe it wasn't available in the stable mirror yet.

Last I checked, the script did work in Stretch, but if something has been broken recently, I will fix as soon as I can get my hands on the stable ISO. I guess that should be within hours from now.

I'm keeping this open until I confirm that everything is fine with Stretch.

**Comment by fbearoff** [comment] 2017-06-18 02:36
The openvpn package is installed, available at /usr/sbin/openvpn, but is not showing up as a running background service

**Comment by Nyr** [comment] 2017-06-18 15:59
82776145f278cd7b2854acc2991f95fb836d832c

ETA for the patch is currently Tuesday. I should've prepared better, but didn't expect Stretch to be released during a weekend... sorry for the inconvenience, I know this isn't ideal for a critical issue.

**Comment by fbearoff** [comment] 2017-06-19 00:06
No worries. Also would like to add, when you do the uninstall option from the script it attempts to remove the openvpn-blacklist package which no longer exists in stretch.

**Comment by Nyr** [comment] 2017-06-20 17:35
I've just commited b2d8c73e1b4d8ce9c3e254717ecc9602eb4394b6, which fixes the uninstaller on Debian 9 and other less important things.

Debian 9 introduces some significant changes including a new configuration structure and new systemd services, but the "classic" configuration structure is still used by default, so no changes on my side for now.

Related to your specific issue, I haven't been able to reproduce. I want to think that whatever happened wouldn't happen with a clean Debian 9 install, but I didn't have time to set up from an ISO and have just tested with DigitalOcean and Vscale images.

If anyone is still experiencing problems with Debian 9, please let me know the details and I'll further troubleshoot. For now, I'm closing this issue.

**Closed by Nyr** 2017-06-20 17:35 UTC

**Comment by fbearoff** [comment] 2017-06-20 23:04
It is working now on my system, thanks!
