### ISSUE TITLE
What ever you did last update you broke it

### ISSUE THREAD

**Issue by AnonLiveStealth** [Nyr/openvpn-install#568] opened 2019-01-10 02:47 UTC
The last update is useless you broke it...Why did you change the way the profiles get edited to change the time length of the profiles? It was fine...Now it won't change from the default time.....Good thing i saved a old version why would you do what you did? lol Makes 0 sense but alright.......

**Comment by Nyr** [comment] 2019-01-10 12:51
Which client software are you using?

If the new version is broken for you, the most likely explanation is that your client software parses the configuration file incorrectly. Please, let me know so I can check this.

If the change causes problems in any client, it will be reverted, but I need to reproduce this first.

**Comment by AnonLiveStealth** [comment] 2019-01-10 17:03
No it's hard to explain has nothing to do with the client its how you
changed the easyrsa file.....Where you change it from 3650 to say 31
days....New profiles wont change to 31 days........Understand what i mean
now? You broke it dude promise you.

**Comment by AnonLiveStealth** [comment] 2019-01-10 17:04
You even put note at where you changed it....What ever you did revert back dude please.

**Comment by Nyr** [comment] 2019-01-10 17:21
Okay, so you are not referring to the latest commit, but an older one.

EasyRSA 3.0.5 uses a shorter expiry time by default than previous versions for the generated certificates. That's why the change was implemented with the v3.0.5 upgrade.

I don't fully understand what you mean, but am almost sure that there isn't a problem with this. If you insist, please explain the issue in your native language as clear as possible and I'll try to use a translator. If someone else understands what @AnonLiveStealth is trying to say, please chime in.

I'm closing this because I don't believe that there is anything wrong in my side.

**Closed by Nyr** 2019-01-10 17:21 UTC

**Comment by vleeuwenmenno** [comment] 2019-01-10 17:47
> Good thing i saved a old version why would you do what you did? lo

You know you can just clone the repo on a specific commit.
If you don't like the changes then do that, but same as @Nyr I'm not sure what's your issue.
I've been using this script for quite a while now and its fine for me.

**Comment by AnonLiveStealth** [comment] 2019-01-10 18:42
I already found the last version pulled it off my other server and works
fine.... The new one is broken wont correctly change the date when making
new profiles...Try the new one with Centos 6 or 7 and watch what i
mean...Go try to make a 30 day profile after you install the new
installer....I bet you will see my issue....

**Comment by AnonLiveStealth** [comment] 2019-01-10 18:43
100% Promise you yes there is a issue so don't believe me its okay i'll
just use the old one thank you!

**Comment by Nyr** [comment] 2019-01-10 18:58
If someone else has an issue or understands whatever this user is trying to say, please open a new thread.
